rabbitmq/rabbitmq-common

mk/rabbitmq-run.mk
There was dependency on non-existient target `virgin-tmpdir`.
=> Fix `run-background-brocker` makefile target

src/rabbit_nodes.erl
As `random:uniform/1` is used only once throughut the codebase, there is probably no sense in adding full-fledged helper module for random generation.
Closes #3
=> Initialize PRNG with unique data

include/rabbit.hrl, src/rabbit_net.erl, src/rabbit_networking.erl, src/rabbit_reader.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/260.
I didn't add a dependency on Ranch yet; I suspect rabbit_common
is used by more than the server, and we would depend on Ranch
even for unrelated things. I will need to check this before
merging.
=> Use Ranch for TCP acceptor pool

src/pmon.erl
Spec states that demonitor/2 should always return #state{}, but it
wasn't the case when pid wasn't found in #state.dict. This made API
unsafe to use, as it could lead to some other process storing incorrect
data as a pmon state.
This patch will prevent exceptions with stacktrace provided at the end of this message, where lists:foldl/3 was used to accumulate result of sequence of pmon:demonitor/2 applications. 
Probably attempt to demonitor something that was not monitored is manifestation of another bug, but I wasn't able to pinpoint it.
```
** {function_clause,
[{pmon,demonitor,
[<23061.2976.0>,
{dict,21,16,16,8,80,48,
{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
{{[[<0.9324.0>|#Ref<0.0.1.31485>]],
[[<0.8783.0>|#Ref<0.0.1.31479>],
[<0.9229.0>|#Ref<0.0.1.31483>]],
[], …
```
=> Make pmon:demonitor/2 respect its contract

src/rabbit_control_misc.erl
Solves [#428](https://github.com/rabbitmq/rabbitmq-server/issues/428)
=> Moves print_cmd_result/2 from rabbit_ctl_misc to rabbit_control_misc

src/rabbit_net.erl, src/rabbit_reader.erl
These were removed by mistake when switching to Ranch.
The file_cache_handler used to be the acceptor doing the obtaining
(before even having an actual socket accepted), then transferring
the ownership to the new process. This has changed a little: now
the reader process claims the socket directly, saving one step.
The buffer tuning is now performed by the reader because Ranch does
not allow operations right after accepting. I have taken a note of
this and will improve this behavior with a future Ranch release.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/446
=> Add file_cache_handler and buffer tuning back

src/rabbit_reader.erl
BEFORE: negotiated frame_max = 1024 is lower than the minimum allowed value (131072)
AFTER: negotiated frame_max = 1024 is lower than the minimum allowed value (4096)
Sorry last one was mistakenly closed
=> fix failed integer value negotiation reporting

include/rabbit.hrl
To accompany https://github.com/rabbitmq/rabbitmq-server/pull/533.
=> New constant for rabbitmq-federation-7

src/rabbit_reader.erl
Fixes rabbitmq/rabbitmq-server#544.
=> Adds handling of exit signals from socket process to rabbit_reader, when terminating channels

src/rabbit_auth_mechanism.erl, src/rabbit_channel.erl, src/rabbit_channel_interceptor.erl, src/rabbit_exchange_decorator.erl, src/rabbit_exchange_type.erl, src/rabbit_policy_validator.erl, src/rabbit_queue_decorator.erl, src/rabbit_queue_master_locator.erl, src/rabbit_registry.erl, src/rabbit_registry_class.erl, src/rabbit_runtime_parameter.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/559
Callbacks to update interceptors.
Related to https://github.com/rabbitmq/rabbitmq-server/pull/578
Callback cause all channels to refresh interceptors list.
=> Update channel interceptors on register/unregister

src/rabbit_misc.erl
* Use lists:keyfind instead of proplists to speed up the management stats
Derives from https://github.com/rabbitmq/rabbitmq-management/issues/41
=> Optimisation

src/rabbit_misc.erl
Looks like all issues were fixed in erlang 17.0. After 1000 thousand invocations of rabbitmqctl on busy machine nothing was lost neither on linux
```
for i in $(seq 1 1000); do ./scripts/rabbitmqctl status 2>&1; done | grep 'cookie hash' | wc -l 
```
nor on windows
```
for /l %x in (1, 1, 1000) do rabbitmqctl.bat status 2>&1 | findstr /c:"cookie hash" >> cookie-hash.txt
```
Opening several ports for single fd is considered undefined behaviour in
erlang. It's safe to replace this whole function with `io:format` when
erlang 17 or later is used. Because writing to standard_error with
io:format is synchronous - after this call has returned data was
definitely sent to the port. And `erlang:halt/` guarantees that this
data will be flushed afterwards.
Closes #53
=> Remove custom stderr formatting

src/rabbit_amqqueue.erl, src/rabbit_misc.erl
`rabbit_channel:handle_method` for `queue.declare` could go into infinite loop, when it tries do define a queue which got somehow corrupted. This fix at least will help with symptoms of this corruption - channel will quickly become unstuck.
Loop happens due to somewhat special handling of `not_found` in 'queue.declare' - it is treated not as an error here, but as a permission to proceed with queue creation. As the base case of recursion in `rabbit_amqqueue:with/4` is actuallly about some unrecoverable error, it makes sense to always return `absent` error here. It will still result in `not_found` error for clients, but internally it'll be handled correctly.
=> Prevent infinite loop on 'queue.declare'

include/rabbit.hrl, src/rabbit_amqqueue.erl, src/rabbit_channel.erl, src/rabbit_misc.erl
Fixes rabbitmq/rabbitmq-server#248.
=> Adds channel_operation_timeout when channels notify queues of shutdown

src/rabbit_channel.erl
As part of rabbitmq/rabbitmq-server#248.
=> Moves channel state update from notify_queues/1 to channel.close handler

include/rabbit_misc.hrl, src/rabbit_health_check.erl, src/rabbit_misc.erl
Introduce node health check used by rabbitmqctl and the management HTTP API.
Moved `rabbit_cli:call_rpc` from the `rabbit` application to `rabbit_misc`, so it can be used by the health checks from `rabbit` and `rabbitmq_management` applications.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/398
=> Add node health check

src/rabbit_auth_backend_dummy.erl, src/rabbit_auth_backend_internal.erl, src/rabbit_types.erl
* Remove modules from rabbitmq-server and add them to rabbitmq-common.
Fixes [#65](https://github.com/rabbitmq/rabbitmq-common/issues/65).
=> Move types and auth_backend modules over from rabbitmq-server.

src/code_version.erl, src/ssl_compat.erl, src/time_compat.erl
Based on dynamic code load in startup/runtime. See https://github.com/rabbitmq/rabbitmq-server/issues/346#issuecomment-169980207
Solves https://github.com/rabbitmq/rabbitmq-server/issues/346 and https://github.com/rabbitmq/rabbitmq-server/issues/347
=> Use dynamic code loading in ssl_compat and time_compat

src/rabbit_queue_master_locator.erl
=> Updates queue_master_location/1 parameter spec from pid() to #amqqueue{}

src/rabbit_reader.erl
...of connection (flow control) state.
This makes it much easier to reason about flow control
state when looking at the management UI or monitoring tools
that poll HTTP API.
Now that rabbitmq/rabbitmq-management#41 is merged, there are
few arguments against always emitting stats.
Fixes rabbitmq/rabbitmq-server#679. Also see rabbitmq/rabbitmq-stomp#70 and rabbitmq/rabbitmq-mqtt#71.
=> Emit stats unconditionally

src/rabbit_amqqueue.erl
`rabbit_amqqueue:info_down/2` was erroneously used insted of
`rabbit_amqqueue:info_down/3`.
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/696
And thanks to this issue it is now preemptively fixed in
https://github.com/rabbitmq/rabbitmq-server/pull/683 )
=> Fix listing of down queues

src/rabbit_amqqueue.erl
It makes no sense to concatenate information about several consumers
into single proplist.
`rabbit_amqqueue:consumers_all/1` is already doing `lists:append/1`, so
it is already capable of handling zero or more consumers reported.
And for `rabbitmqctl list_consumers` we need to support printing
lists-of-lists, for the same purpose of reporting zero or more consumers.
Another part for https://github.com/rabbitmq/rabbitmq-server/issues/701
=> Fix `rabbitmqctl list_consumers`

src/rabbit_reader.erl
Authentication in AMQP 0-9-1 is a two step process:
* Authentication
* connection.open
Vhost is selected at the 2nd step, so in authentication success
events we don't have any information about the vhost. It is emitted,
however, as part of a "connection created" event immediately after.
Fixes https://github.com/rabbitmq/rabbitmq-event-exchange/issues/13.
=> Exclude vhost from authentication success events (see below)

src/rabbit_misc.erl
Part of proposal to fix https://github.com/rabbitmq/rabbitmq-management/issues/75 on stable
=> Add a special value to term_to_json to allow encoding empty JSON objects

src/rabbit_networking.erl
Recent version of Windows, Linux and FreeBSD use this IANA range (or
its subset) - according to
https://en.wikipedia.org/wiki/Ephemeral_port
There are several reasons for this change:
- SELinux could prevent opening of non-ephemeral port without explicit
declaration - that's why redhat package already does patching of
this value.
- IPv6 testing process can interfere with startup of some legitimate
app which doesn't expect that something else will be listening on
that port. While it may sound as an unlikely event, crashes due to
improper usage of ephemeral ports in other packages constantly
happen on our CI systems.
=> Use IANA ephemeral port range for ipv6 checks

src/rabbit_networking.erl
Fixes https://github.com/rabbitmq/rabbitmq-trust-store/issues/14
Support `verify_fun` format like in [otp ssl](http://erlang.org/doc/man/ssl.html)
Removed old code, since we require R16B03.
=> Support otp style verify_fun ssl option

mk/rabbitmq-run.mk
I attempted to use the pattern used in the ``Makefile`` that is in multiple RabbitMQ repos for changing the config file without any success:
```Makefile
WITH_BROKER_TEST_MAKEVARS := \
RABBITMQ_CONFIG_FILE=$(CURDIR)/etc/rabbit-test
```
This did not allow for ``make run-broker`` to execute successfully with my test configuration.
This change allows for the setting of ``TEST_CONFIG_FILE`` in the project ``Makefile`` without issue.
Perhaps my problem with the current pattern is user error, but I did not see the behavior of ``WITH_BROKER_TEST_MAKEVARS`` that would allow for the override of ``RABBITMQ_CONFIG_FILE`` to successfully work with ``make run-broker``.
My project's ``Makefile`` now reads as:
```Makefile
TEST_CONFIG_FILE=$(CURDIR)/etc/rabbit-test
```
and works as I would expect. This …
=> Only set TEST_CONFIG_FILE if not set

src/rabbit_amqqueue.erl, src/rabbit_channel.erl, src/rabbit_control_misc.erl, src/rabbit_misc.erl, src/rabbit_networking.erl
Complement for https://github.com/rabbitmq/rabbitmq-server/pull/683
- `rabbit_control_misc:wait_for_info_messages/5` can wait for results of
more than one emitting map.
- Stop passing arround InfoItemKeys in
`rabbit_control_misc:wait_for_info_messages/5`, the same information
could be directly encoded in DisplayFun closure.
- Add `emit` to function names, to avoid confusion with regular ones
which return result directly.
=> Support for parallel info emission

src/rabbit_ct_broker_helpers.erl
Fixes https://github.com/rabbitmq/rabbitmq-auth-backend-cache/issues/2
Plugins can be set as list of atoms using `rabbit_ct_helpers:set_config(Config, {plugins, [plugin, plugin]})`.
=> Specify plugins to start test broker with

src/rabbit_exchange_type.erl
Add new callbacks to `rabbit_exchange_type` behaviour to display type-specific exchange info.
Related to https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/pull/46
And https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/3 issue.
=> Support for type-specific exchange info

include/rabbit.hrl, src/rabbit_heartbeat.erl
Introduced new constants for worker and supervisor shutdown timeouts.
Set default worker timeout to 30 seconds.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/541
=> Bounded OTP worker timeout

src/rabbit_control_misc.erl
Example of stacktrace - https://github.com/rabbitmq/rabbitmq-server/issues/709
=> Don't spew stacktrace on join when already member

src/rabbit_amqqueue.erl, src/rabbit_channel.erl, src/rabbit_health_check.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/818
Also:
- fix queues health-checking - `rabbit_amqqueue:info_all` was expecting
vhost argument, but was passed `[pid]` instead. So no health check was
actually performed. Proper way is to iterate over all vhosts.
- delegate all error/timeout handling to `rabbit_cli`, so no more magic
`70` and `68` and no more `case`-ing on `badrpc` that is already
present in other places.
=> Make `rabbit_health_check` completely node-local

src/rabbit_misc.erl, src/rabbit_reader.erl
Remake of #101 - now connection name in managment UI and HTTP UI is untouched.
In addition to https://github.com/rabbitmq/rabbitmq-server/issues/104
=> Use user specified connection name in logs

src/rabbit_ct_broker_helpers.erl
Required for https://github.com/rabbitmq/rabbitmq-web-stomp/pull/63
=> Add web-stomp port generation to common test helpers

src/rand_compat.erl
`rand` automatically seeds implicit state generator with unique values,
but for `random` we need to do it manually. Corresponding code was lost
in 76f0dbb6.
=> Make `rand_compat:uniform/1` more uniform

include/rabbit.hrl, src/rabbit_ct_broker_helpers.erl, src/rabbit_networking.erl, src/rabbit_reader.erl, src/rabbit_types.erl
Part of rabbitmq/rabbitmq-server#500 and rabbitmq/rabbitmq-server#627.
Lays ground work for rabbitmq/rabbitmq-server#607.
=> Keep track of connections, introduce per-vhost limits

src/credit_flow.erl, src/rabbit_amqqueue.erl
Checking for slaves is not enough to decide whether to stop, as sometimes during partial partitions the status gets completely messed up.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/953
=> Check mirrored queue on node down

LICENSE, LICENSE-MIT-Erlware-Commons, Makefile, src/ec_semver.erl, src/ec_semver_parser.erl, src/rabbit_misc.erl, test/unit_SUITE.erl
We need to support prerelease suffix, to use for nightlies and release candidates.
Includes special case for 3.6.6, which is a breaking 'patch'. 💔
Uses https://github.com/erlware/erlware_commons - see commit message for justification.
=> Broaden version format support

src/rabbit_peer_discovery_backend.erl, src/rabbit_types.erl
A new behaviour for pluggable cluster peer discovery.
Borrowed from [1] with a bit of renaming and a blessing from Gavin M. Roy.
1. https://github.com/aweber/rabbitmq-autocluster/blob/master/src/autocluster_backend.erl
Part of rabbitmq/rabbitmq-server/issues/486.
=> Introduce rabbit_peer_discovery_backend

src/rabbit_common.app.src
While they don't need to be started, we do depend on them,
so should list them as dependencies. This will ensure that
they will be included when building releases that include
the Erlang client.
Fixes https://github.com/rabbitmq/rabbitmq-erlang-client/issues/72.
=> Add dependencies on compiler and syntax_tools

LICENSE, LICENSE-MIT-Mochi, src/rabbit_http_util.erl, src/rabbit_misc.erl, src/rabbit_numerical.erl, src/rabbit_semver.erl, src/rabbit_semver_parser.erl, test/unit_SUITE.erl
Part of https://github.com/rabbitmq/rabbitmq-common/issues/139
They are pulled by amqp_client and can create conflicts with
other libraries when developers build releases with the Rabbit
client and Mochiweb, for example.
* mochiweb_util -> rabbit_http_util
* mochinum -> rabbit_numerical
* ec_semver -> rabbit_semver
=> Rename mochinum, mochiweb_util and ec_semver modules

mk/rabbitmq-components.mk
The Ranch update is for SNI. See https://github.com/rabbitmq/rabbitmq-server/issues/789
The Cowboy update is because I noticed it was outdated for no good reasons (just one commit behind but since it's fixing a bug with Websocket we might as well use it).
=> Update Ranch and Cowboy

include/rabbit.hrl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/847
Loads shutdown timeout for supervisors and workers from application environment.
Can have impact on performance. Therefore needs to be perf-tested.
=> Configurable shutdown timeouts

src/rabbit_channel.erl
Fixes:https://github.com/rabbitmq/rabbitmq-common/issues/162
to reproduce the problem:
```
curl -i -u guest:guest -H "content-type:application/json" \
-XPUT -d'{"auto_delete":false,"durable":false,"arguments":{"x-queue-mode":"wrong"}}' \
http://localhost:15672/api/queues/%2f/卓匃屟尢桨
```
=> Change the message format

mk/rabbitmq-dist.mk
Detect dependencies with `mix.exs` file and build `*.ez` archives for them using the [Archive.Build.All](https://github.com/hairyhum/mix_task_archive_deps) Mix task.
The task lib is installed using `Mix.Archive.Install` if not present in `MIX_ARCHIVES` already.
Required for rabbitmq/rabbitmq-auth-backend-uaa#5
rabbitmq/rabbitmq-auth-backend-uaa#3
=> Build *.ez archives for Elixir dependencies

src/rabbit_binary_parser.erl
Note that both `l` and `L` fields are encoded
the same way for historical and backwards compatibility
reasons.
See https://github.com/rabbitmq/rabbitmq-server/issues/1093#issuecomment-276351183,
http://www.rabbitmq.com/amqp-0-9-1-errata.html, and section
4.2.1 of the spec for details.
Closes rabbitmq/rabbitmq-server#1093.
=> Decode L (long-long-int) fields

src/rabbit_reader.erl
=> Clean channel metrics when channel exits with an uncontrolled termination

mk/rabbitmq-components.mk
The new feature of Cowboy 1.1.0 of interest to RabbitMQ is the possibility to serve static files from Erlang application .ez archives. This will allow us to get rid of the plugins expansion during RabbitMQ
startup.
Cowboy 1.1.0 also comes with a stricter URL parser. In particular, `+` characters are not converted to spaces anymore! They are left alone. Users of the HTTP API must make sure that their requests are encoded using path segment encoding, not query string encoding (where `+` are converted to spaces).
References ninenines/cowboy#1070.
References ninenines/cowboy#1080.
[#136779967]
=> mk/rabbitmq-components.mk: Switch to Cowboy 1.1.0

src/rabbit_cert_info.erl
Those functions are used by rabbitmq-erlang-client. That client shouldn't depend on the broker, so let's move those functions (which do not depend on the broker itself) to a module in rabbitmq-common.
The `rabbit_ssl` module stays there and acts as a wrapper around the new `rabbit_cert_info` module. The former still contains functions which depend on the broker however.
[#118490793]
=> rabbit_cert_info: New module with functions moved from `rabbit_ssl`

src/rabbit_channel.erl
For queue.{bind, unbind}. To stick to the previous behavior.
Part of rabbitmq/rabbitmq-server#1099
=> Skip topic authorisation if exchange doesn't exist

mk/rabbitmq-run.mk
Support for reading static files from Erlang .ez archives was added to Cowboy and various RabbitMQ plugins were updated to take advantage of the new API.
So this commit restores commit 59cd2ca5e48c1a011a0ae18392d20272215a3783.
It was reverted in 5079a36e0612f8739eb17149d6ae17c002396c74 because Cowboy didn't have this support at the time.
Signed-off-by: Gerhard Lazu <gerhard@rabbitmq.com>
[#118562759, #136622317]
=> Restore "rabbitmq-run.mk: Remove $RABBITMQ_PLUGINS_EXPAND_DIR"

src/gen_server2.erl
CRASH REPORT Process <0.1633.0> with 0 neighbours crashed with reason: bad function undefined in gen_server2:terminate/3 line 1138
=> Initialise stats-related functions in enter_loop

src/rabbit_misc.erl
Stacktrace elements can also be a 4-element tuples like
`{module,function,[attributes],[]}`
But as we only care about an `undef` error fact, it makes no sense
to inspect stacktrace contents.
=> Better error handling for module attributes

src/rabbit_core_metrics.erl
This allows propagating short-lived stats which otherwise would
be missed in some aggregated stats as vhost or exchange
Part of https://github.com/rabbitmq/rabbitmq-management/issues/353
[#140662033]
=> Mark selected core metrics for deletion by the collector

src/app_utils.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/1141
Addresses rabbitmq/rabbitmq-server#1122
When RabbitMQ server is stopping it stops all plugin applications.
If an application fails to stop - it can make entire erlang node
unresponsive.
Log will clarify which application is stopping at a moment.
=> Log every stopping application

mk/rabbitmq-dist.mk
One of the thing RabbitMQ expects from a plugin is a dependency on the
`rabbit` app. The problem is that `mix run` tries to start plugin app,
which leads to an unsuccessful attempt to start `rabbit` app.
=> Allow building plugins written in Elixir

mk/rabbitmq-dist.mk
After changing any .erl-file and running `make dist` .ez files are
regenerated. But this is not the case for Elixir plugins - so it's
necessary to clean `plugins/` to refresh.
The difference is that for erlang.mk projects there is an explicit
dependencies on `ebin`, `include` and `priv` folder content -
https://github.com/rabbitmq/rabbitmq-common/blob/adaa9ac03943055ad68017df3b4272e8bf93bc3a/mk/rabbitmq-dist.mk#L52
But there were no similar rule around
https://github.com/rabbitmq/rabbitmq-common/blob/adaa9ac03943055ad68017df3b4272e8bf93bc3a/mk/rabbitmq-dist.mk#L91
So I've tried to add some reasonable dependencies there. I'm not so sure about `_build/dev/...` choice, but at least it works.
=> Regenerate Elixir-based .ez-s after changes

src/rabbit_amqqueue.erl
Ensures that newly forgotten nodes are not selected for promotion, otherwise restarted slaves might not be able to bring up the queues.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1213
=> Promote slaves only for actual members when forgetting cluster nodes

src/rabbit_amqqueue.erl, src/rabbit_backing_queue.erl, src/supervisor2.erl
Required for https://github.com/rabbitmq/rabbitmq-server/pull/1158
rabbitmq/rabbitmq-server#1146
=> Support per-vhost stop/start API for backing queue behaviour.

src/app_utils.erl, src/supervisor2.erl
Reverts the implementation of `supervisor2:prep_stop` as it is not necessary anymore with the VM shutdown. 
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1216
=> Make rabbit application transient

src/rabbit_reader.erl
For some "connection closed" cases. In others the changes required are too risky for `3.6.x`.
=> Augment closed connection log entries

src/supervisor2.erl
Otherwise the child might not be restarted on failure under certain
circumstances (see the code to reproduce the issue below).
Here's the sequence of events leading to the issue.
1. A child crashes multiple times forcing the supervisor2 to
delay-restart it.
2. Upon scheduling the delayed restart, the supervisor calls
state_del_child/2 which sets child's pid to undefined.
3. After the delay, on restart attempt the child crashes before
replying to the supervisor.
4. The supervisor schedules another restart attempt via
try_again_restart/3. Before that restart/3 would try to mark the
child as being restarted by means of calling restarting/1 on
child's pid. But since the pid is undefined, the function keeps it
unchanged.
5. When the supervisor handles the try_again_restart cast, it expects
the …
=> [supervisor2] Mark child restarting when delaying restart.

.travis.yml, README.md
* No need to use `sudo` which will cause builds to start quite a bit faster.
* Use Travis CI's cache feature to keep from having to build elixir 1.4.4 every time.
=> Fix Travis CI build

include/rabbit.hrl, src/rabbit_amqp_connection.erl, src/rabbit_auth_backend_internal.erl, src/rabbit_channel.erl, src/rabbit_types.erl, test/unit_SUITE.erl
The expansion is done inside the internal authz backend
and the variables to expand are provided in a map from
the context parameter. This decoupling allows to provide
different variables to expand based on the caller context
(e.g. add other variables to expand from the MQTT plugin).
References rabbitmq/rabbitmq-server#1229
=> Expand username & vhost variables in topic perms

src/rabbit_misc.erl, test/unit_SUITE.erl
Even thought I was leaning towards EUnit at first, since CT was already there
and is already used for unit testing, it made the choice easy. I didn't
like the fact that I had to export the function to test it, but maybe
I'm missing something.
As for the test itself, I tried a couple of approaches and finally
settled on "if it starts with 'Erlang/OTP (MAJOR_VERSION)`, we're good.
Happy to hear better alternatives.
=> Add OTP version to server properties

src/vm_memory_monitor.erl
Prior to this change, on a host with 16GB of RAM, RabbitMQ was reporting
total memory as `13719 MiB (14385987584 bytes)`. This was obviously
incorrect, the host has 16384MiB of RAM.
Other notable utilities that use sysctl to report total memory on OS X:
* Ohai (Chef): https://github.com/chef/ohai/blob/v13.2.0/lib/ohai/plugins/darwin/memory.rb#L25
* Facter (Puppet): https://github.com/puppetlabs/facter/blob/3.7.0/lib/src/facts/osx/memory_resolver.cc#L17
Using `/usr/bin/env sysctl` since:
* OS X: `/usr/bin/sysctl`
* FreeBSD & OpenBSD: `/sbin/sysctl`
=> Use sysctl to get the total memory on Darwin (OS X)

src/rabbit_log.erl
Log qualifiers should be compatible with pre-3.7 qualfiers.
`rabbit_log_...` should be used only as fake module names
for lager parse-transform.
[#149634975]
=> Revert the change of log qualifiers.

mk/rabbitmq-components.mk
When non-English locale is used, detached HEAD magic stops working
=> Fix dep fetching on detached HEAD

src/gen_server2.erl, src/rabbit_core_metrics.erl, src/rabbit_event.erl, test/gen_server2_test_server.erl, test/unit_SUITE.erl
Fixes #196, follow up to #197 
Stop the stats emission timer before waiting for the backoff timeout.
Includes some changes to the `gen_server2` stats emission callback logic. Callbacks now only emit stats, while timer and `gs2_state` is managed by `gen_server2` itself. It makes it easier to control the timer and test.
=> Stop gen_server2 stats emissions when preparing to hibernate

src/vm_memory_monitor.erl
System RSS reporting functions can take some time to execute, especially when called concurrently. To optimise that on hot code paths we cache the last value for 500 ms.
It won't affect regular memory collection functions for memory alarms and management stats (which happens every 1 sec), only calls from `file_handle_cache`, which can be called concurrently.
Addresses rabbitmq/rabbitmq-server#1343
=> Optimise memory reporting to call less system memory reports.

src/vm_memory_monitor.erl
Fixes rabbitmq/rabbitmq-server#1343
=> Revert to using erlang:memory() on Win32

Makefile, src/vm_memory_monitor.erl
=> Use recon_alloc:memory to get process RSS

LICENSE-BSD-recon, Makefile, src/app_utils.erl, src/vm_memory_monitor.erl
Fixes #224.
Also see rabbitmq/rabbitmq-erlang-client#92 and https://github.com/rabbitmq/rabbitmq-server/pull/1389.
=> Use recon_alloc to get memory info on Win32, /proc on Linux, ps for other OS types

src/vm_memory_monitor.erl
Follow-up to #224
* R16 compatibility
* Trap noproc in an additional case
=> Fix issues uncovered after merging #224

Makefile, src/supervisor2.erl
`supervisor`'s state change from `otp-18` and add a field, but `supervisor2` didn't.
So, when i do release upgrade it will print a error msg:
```
<0.1153.0> reason: {'EXIT',
{{badrecord,state},
[{supervisor,get_callback_module,1,
[{file,'supervisor.erl'},{line,266}]},
{release_handler_1,get_supervisor_module,1,
[{file,'release_handler_1.erl'},{line,684}]},
{release_handler_1,get_master_procs,3,
[{file,'release_handler_1.erl'},{line,605}]},
{lists,foldl,3,[{file,'lists.erl'},{line,1262}]},
{release_handler_1,eval,2,
[{file,'release_handler_1.erl'},{line,375}]},
{lists,foldl,3,[{file,'lists.erl'},{line,1262}]},
{release_handler_1,eval_script,5,
[{file,'release_handler_1.erl'},{line,102}]},
{release_handler,eval_script,5,
[{file,'release_handler.erl'},{line,368}]}]}}
release_handler: cannot …
```
=> fix supervisor2's state for get {badrecord,state} error when release upgrade

src/vm_memory_monitor.erl
This is due to a scenario in which the Erlang VM allocator stats report a huge increase in memory consumption which is only reflected in VSS increase, not RSS
PT #152081051
=> Default mem calc strategy should be "rss"

src/gen_server2.erl, src/rabbit_core_metrics.erl
Performance gains on the `gen_server2` simplification are not easy to measure, but `cast` is such a frequent operation that might have some impact.
=> Minor performance improvements

src/vm_memory_monitor.erl
Helper functions for rabbitmq/rabbitmq-management#499
[#151472607]
=> An API to get non-cached process memory.

src/app_utils.erl
This is a backport of #194 https://github.com/rabbitmq/rabbitmq-server/issues/1216
[#152310581]
=> Start `rabbit` application as transient.

src/rabbit_backing_queue.erl
This can be used to handle generic messages that the parent `gen_server2` wishes to pass to backing queues. Initially used for the bump_reduce_memory_use message.
Part of rabbitmq/rabbitmq-server#1393
=> Introduce handle_info callback

mk/rabbitmq-components.mk, mk/rabbitmq-mix.mk
References rabbitmq/rabbitmq-server-release#61.
=> Add `rabbitmq-mix.mk` which is copied to Elixir components when we create the source archive

src/rabbit_peer_discovery_backend.erl
Note that this should not be a breaking change: all known implementations of this (barely shipped) interface currently ship with RabbitMQ and the callback is optional.
Part of rabbitmq/rabbitmq-peer-discovery-common#5.
[#153615554]
=> Peer discovery backend: add an optional init callback

mk/rabbitmq-early-test.mk, src/rabbit_misc.erl
This is #254 branched off of `master` for simplified testing.
=> Hide common test node (master)

mk/rabbitmq-early-test.mk, src/rabbit_misc.erl
This is #254 rebased onto v3.7.x.
=> Hide common_test node (3.7.x)

mk/rabbitmq-early-test.mk, src/rabbit_misc.erl
As commented in `rabbitmq-early-test.mk`:
> We start the common_test node as a hidden Erlang node. The benefit is that other Erlang nodes won't try to connect to each other after discovering the common_test node if they are not meant to.
>
> This helps when several unrelated RabbitMQ clusters are started in parallel.
=> Hide common_test node (3.6.x)

src/rabbit_core_metrics.erl, src/rabbit_event.erl
This is #258 rebased onto `master`.
=> Delete metrics for all deleted queues in 4 ETS operations (master)

src/rabbit_core_metrics.erl, src/rabbit_event.erl
Reverts rabbitmq/rabbitmq-common#259.
`ets:select_replace/2` is not available in OTP 19.3 😢.
=> Revert "Delete metrics for all deleted queues in 4 ETS operations (master)"

src/rabbit_core_metrics.erl, src/rabbit_event.erl
Rather than using 6 ETS operations per deleted queue, build a match
spec for every 1000 queues that uses `ets:select_replace/2` to delete
metrics in fewer ETS operations.
Great suggestions @michaelklishin & @hairyhum!
https://github.com/rabbitmq/rabbitmq-server/commit/ee0951b1b3c202eb261ad1830f28ab81904a7334#comments
This should be merged together with rabbitmq/rabbitmq-server#1526
For initial context, see rabbitmq/rabbitmq-server#1513.
Partner-in-crime: @essen
=> Delete metrics for all deleted queues in 4 ETS operations (v3.7.x)

include/rabbit.hrl
Part of rabbitmq/rabbitmq-server#1590.
=> Introduce MAX_SUPPORTED_PRIORITY

mk/rabbitmq-run.mk, src/delegate.erl, src/rabbit_pbe.erl, src/vm_memory_monitor.erl
This is one of the PRs that makes RabbitMQ build successfully on Erlang/OTP 21.
OTP 21 deprecated `erlang:get_stacktrace/0` in favor of a new
try/catch syntax. Unfortunately that's not realistic for projects
that support multiple Erlang versions (like us) until OTP 21 can be
the minimum version requirement. In order to compile we have to ignore
the warning. The broad compiler option seems to be the most common
way to support compilation on multiple OTP versions with `warnings_as_errors`: if we use
a function-specific option it will fail on the releases where the function is not deprecated.
[#157964874]
=> Compile on Erlang/OTP 21

src/rabbit_nodes_common.erl
Improves rabbitmq/rabbitmq-server#1654
Reported via:
https://groups.google.com/d/msg/rabbitmq-users/YgtY4R_heI0/AZFs5RPTCgAJ
VESC-906
Example output if `erl` can't be found. Tested via hard-coding the `Exe` argument to `do_ensure_epmd` to `"foofoobar"`:
```
2018-09-27 12:25:38.440 [error] <0.402.0> ensure_epmd: unable to find executable 'erl' in PATH: '/home/lbakken/development/erlang/installs/21.1/erts-10.1/bin:/home/lbakken/development/erlang/installs/21.1/bin:...'
```
=> Improve error case if erl / erl.exe is not in PATH

src/rabbit_net.erl
It has been reported that in order to use the Erlang client, the
Erlang/OTP source must be available. This is due to one include
file that rabbit_net required. This dependency has been removed.
Instead of calling is_record(sslsocket) the macro ?IS_SSL will
now perform the same test manually (check that it is a tuple,
that the size is correct and that the first element equals sslsocket).
The tuple has not changed in a very long time so doing this
manually is at least as safe as including this private header
file (it could be removed or moved at any time).
Once Erlang/OTP 22 gets out and we know how sockets will be
represented with the NIF implementation, we could revise this
and check whether the socket is one that gen_tcp accepts
(currently it's a port, but this will probably change when …
=> Remove dependency on erlang-src

Makefile, include/rabbit.hrl, include/rabbit_core_metrics.hrl, mk/rabbitmq-run.mk, src/credit_flow.erl, src/file_handle_cache_stats.erl, src/pmon.erl, src/rabbit_core_metrics.erl, src/rabbit_net.erl
See: https://github.com/rabbitmq/rabbitmq-server/pull/1706
=> Quorum queues

mk/rabbitmq-run.mk
Remove extra "1" in seq command.  Previously, as an example with
NODES=2, will run `seq 2 1` which produces no items to iterate, so the
entire stop-node loop does not execute and the brokers are left
running.
(This should qualify as an Obvious Fix for CLA purposes)
=> rabbitmq-run.mk: Fix stop-brokers with NODES > 1

mk/rabbitmq-components.mk
I've checked a few Cowboy based plugins and didn't see an issue running the tests. The Ranch update just adds PROXY protocol so no big change from 1.6.2.
=> Update Cowboy to 2.6 and Ranch to 1.7

src/rabbit_backing_queue.erl
Allow the backing queue implementation to instruct the amqqueue process
on how to proceed when a message duplicate is encountered.
* {true, drop} the message is a duplicate and should be ignored
* {true, reject} the message is a duplicate and the publisher should
receive a rejection
* false the message is not deemed a duplicate
* true kept for backward compatibility, equivalent to {true, drop}
Signed-off-by: Matteo Cafasso <noxdafox@gmail.com>
=> rabbit_backing_queue: extend is_duplicate callback return values

src/rabbit_misc.erl, src/rabbit_runtime.erl
A module for functions that provide access to runtime data.
=> Introduce rabbit_runtime

include/rabbit.hrl
Related to https://github.com/rabbitmq/rabbitmq-server/pull/1812
Message size of 2GB is still too big, considering there can be more than just a message body in the distribution message.
Also bogger messages are more dangerous for failure detection, because heartbeats and message replication are using the same port.
=> Reduce max message size to 512MB.

src/rabbit_amqp_connection.erl
A continuation to rabbitmq/rabbitmq-server#1538.
Some users on the mailing list report stacktraces similar to what rabbitmq/rabbitmq-server#1538 addressed. Looks like in those cases the connection terminates normally, which the code in question did not handle. If we can't retrieve connection parameters, assume they are blank instead of failing with an exception.
=> Be more defensive when requesting connection parameters

src/rabbit_heartbeat.erl
If the negotiated heartbeat timeout is 10 seconds, this will ensure the first frame is sent at 5 seconds. Previously it took two intervals (10 seconds total) to discover a difference in the `send_oct` value, which would trigger a heartbeat.
=> Ensure first heartbeat frame is sent to clients at expected interval

src/rabbit_core_metrics.erl
* Add single active consumer flag in consumer metrics
* Add function to update consumer metrics when a consumer is promoted
to single active consumer
[#163089472]
References rabbitmq/rabbitmq-management#649
=> Integrate single active consumer with metrics

src/rabbit_misc.erl, src/rabbit_pbe.erl
They trigger warnings in rabbit. This can be merged independently of the upcoming rabbit PR.
=> Fix many Dialyzer warnings

mk/rabbitmq-build.mk, src/rabbit_log.erl
Add new external sink to able log LDAP message to different file.
This is a part of rabbitmq/rabbitmq-auth-backend-ldap#105.
=> Add lager sink for ldap

src/rabbit_pbe.erl
Some new ciphers have been added. Others will be added once
crypto exposes an interface to get cipher information.
I have opened https://bugs.erlang.org/browse/ERL-864 and will work on a patch to make crypto expose this information. This should take only a few hours.
=> Fix rabbit_pbe for OTP-22

src/gen_server2.erl, src/rabbit_pbe.erl
This depends on https://github.com/erlang/otp/pull/2186 so should not be merged yet.
A good cleanup of this module should be planned once we support OTP-22+. We can remove more than half of the module when that happens.
=> Make rabbit_pbe work for OTP-22

src/rabbit_pbe.erl
The cipher was not available via the EVP interface before
Erlang/OTP-22.
Note that the ciphers aes_..._ctr were added in OTP-22 so no need to blacklist them.
This is for master. For v3.7.x please cherry-pick the commit from the previous PR and then this commit.
=> We don't support aes_ctr before OTP-22

src/vm_memory_monitor.erl
There are cases (e.g. inside LXC) where the unit reported in /proc/meminfo uses
KB instead of kB. Handle this case.
=> vm_memory_monitor: handle KB as well as kB

src/rabbit_misc.erl
Better fix for https://github.com/rabbitmq/rabbitmq-common/issues/313 that closes https://github.com/rabbitmq/rabbitmq-common/issues/315
=> Support both PID_EXT and NEW_PID_EXT simultaneously

src/rabbit_misc.erl
The `creation` field might not fit into one byte which makes the `PID_EXT` format unsuitable for this case.
The `NEW_PID_EXT` format is supported since Erlang 19.0, so it is safe to always use it, no matter the value of `creation`, because RabbitMQ 3.7+ requires at least Erlang 19.3+.
References #313.
=> rabbit_misc: Generate a `NEW_PID_EXT`-based binary in compose_pid/4

src/rabbit_pbe.erl
We disable them when compiling with Erlang <22 because they do not work, and on 22+ for the time being for consistency. We can support them and stream ciphers once we support only 22+ (see added comment). They are also not terribly interesting for what `rabbit_pbe` is used for so it's not a big loss anyway.
=> Don't support aes_ctr ciphers until OTP-22+

src/rabbit_ssl_options.erl
Erlang 22 will introduce TLS 1.3, but at the time of this commit, only the server side is implemented. If the Erlang client requests TLS 1.3, the server will accept but the client will either hang or crash.
So for now, just blacklist TLS 1.3 to avoid any issues, even on the server side, just to be safe.
This should be backported to `v3.7.x` if accepted.
[#165214130]
=> rabbit_ssl_options: Blacklist TLS 1.3 until Erlang client implementation is finished

src/rabbit_core_metrics.erl
Part of rabbitmq/rabbitmq-server#1904.
[#165548314]
=> channel_exchange_metrics now has one more metric: dropped unroutable messages

mk/rabbitmq-run.mk, src/rabbit_misc.erl, test/unit_SUITE.erl
The version check is relaxed. The real check is now made by the feature flags subsystem.
References rabbitmq/rabbitmq-server#2028.
=> Backport RabbitMQ compatible versions check

src/gen_server2.erl, test/unit_SUITE.erl
These functions utilize proc_lib:stop, which in turn utilizes sys:terminate.
They were introduced in
https://github.com/erlang/otp/commit/9d7d1207ff1240b9711f192deb0893c3a044a3d8.
Closes: #266
=> Add stop{1,3} functions to gen_server2

src/rabbit_log.erl
There is ldap sink name, but when I made a PR that added this sink I forgot to add it to category()
=> add forgotten ldap type

src/file_handle_cache.erl
These should be taken into account into the limits, but always be granted.
Three file handles are reserved on startup for the wal, segment writer and a DETS table,
the rest must be reserved by the queues themselves using `set_reservation/0` or
`set_reservation/1`.
=> Reserve file handles for quorum queues

src/rabbit_nodes_common.erl
* Use `noinput`
* Use `-s erlang halt` to skip small `eval` overhead
* Use `no_dot_erlang` boot file since we do not want user customizations to interfere
FWIW I can't reproduce the rogue-`ra` issue.
=> epmd-starter improvements

.gitignore, include/rabbit.hrl, mk/rabbitmq-build.mk, mk/rabbitmq-dist.mk, mk/rabbitmq-run.mk, src/rabbit_env.erl, src/rabbit_log.erl, test/rabbit_env_SUITE.erl
This pull request is part of the effort to move rabbitmq-server(8) scripts to Erlang code and transform the `rabbit` application in a regular Erlang/OTP application (rabbitmq/rabbitmq-server#2180).
This patch covers two main areas:
1. It introduces a new module called `rabbit_env`. It is responsible to create a context based on RabbitMQ environment variables and default settings. The reorganized startup sequence now relies on this context to configure Erlang applications and set RabbitMQ up.
2. The way the `rabbit` application is distributed is now the same as any plugins: it is now packaged as an `.ez` archive. This simplifies our Makefiles and makes RabbitMQ startup in a development environment identical to a production RabbitMQ (installed from packages for instance).
=> Introduce `rabbit_env` module

mk/rabbitmq-run.mk
No longer applies after merge of rabbitmq/rabbitmq-server#2180
=> Remove RABBITMQ_GENERATED_CONFIG_DIR

src/rabbit_writer.erl
This PR gives possibility to configure gc threshold - how often gc will be run (if any).
According to erlang doc:
*Improper use can seriously degrade system performance.*
This performance degradation accually occurs on production env.
Please also check:
https://groups.google.com/forum/#!searchin/rabbitmq-users/nycz%7Csort:date/rabbitmq-users/hVlXjmG6suk/f43miaI-AQAJ
=> make garbage collector threshold configurable

mk/rabbitmq-dist.mk, mk/rabbitmq-run.mk, src/rabbit_env.erl, src/rabbit_nodes_common.erl, test/rabbit_env_SUITE.erl, test/unit_SUITE.erl
I.e. we record the fact that a particular value:
* is the default value, or
* comes from an environment variable, or
* comes from querying a remote node
This required a significant refactoring of the module, which explains the large diff.
At the same time, the testsuite was extended to cover more code and situations.
This work permits us to move remaining environment variables checked by `rabbit` to this module. They include:
* `$RABBITMQ_LOG_FF_REGISTRY`
* `$RABBITMQ_FEATURE_FLAGS`
* `$NOTIFY_SOCKET`
References rabbitmq/rabbitmq-server#2180.
=> rabbit_env: Record variables' origin

test/rabbit_env_SUITE.erl
This happens when testing mixed-versions cluster in CI. This fixes the test after commit 87eb3b0d99e6c109ab8337b859361a250d0efba9.
This is a followup patch to #352 and is part of rabbitmq/rabbitmq-server#2180.
[#170149339]
=> rabbit_env_SUITE: Check if $RABBITMQ_FEATURE_FLAGS is overridden

src/rabbit_misc.erl
Same as https://github.com/rabbitmq/rabbitmq-server/pull/2233 for **v3.7.x**.
(We actually need this for a v3.7.x release)
=> Handle and raise protocol error for absent queues assumed to be alive

src/rabbit_env.erl, test/rabbit_env_SUITE.erl
The env var is now handled directly by rabbitmq_prelaunch rabbit_boot_state_systemd
Should be merged after https://github.com/rabbitmq/rabbitmq-server/pull/2231
=> Remove systemd_notify_socket

src/rabbit_env.erl, test/rabbit_env_SUITE.erl
It is used to specify additional configuration files when using the Cuttlefish format.
Required by rabbitmq/rabbitmq-server#2258.
=> rabbit_env: Add `$RABBITMQ_CONFIG_FILES`

erlang.mk, mk/rabbitmq-tools.mk
Before I update erlang.mk across all repos, wanted to double-check that this works for you @dumbbell on FreeBSD. Maybe @lukebakken or @acogoluegnes would like to weigh in with their Linux perspectives. This is the output that I'm getting in `deps/rabbit`:
```
make query-deps
rabbit: rabbitmq_cli git_rmq https://github.com/rabbitmq/rabbitmq-cli master
rabbit: syslog git https://github.com/schlagert/syslog 3.4.5
rabbit: cuttlefish hex https://hex.pm/packages/cuttlefish 2.2.0
rabbit: ranch hex https://hex.pm/packages/ranch 1.7.1
rabbit: lager hex https://hex.pm/packages/lager 3.8.0
rabbit: rabbit_common git_rmq https://github.com/rabbitmq/rabbitmq-common master
rabbit: ra git https://github.com/rabbitmq/ra.git master
rabbit: sysmon_handler hex https://hex.pm/packages/sysmon_handler 1.2.0 …
```
=> Add erlang.mk query-deps

.travis.yml, include/rabbit.hrl
We already announced and document that RabbitMQ 3.7.x requires Erlang/OTP 21.3.
This commit makes it effective. This allows us to use the new `try Class:Reason:Stacktrace` syntax introduced in Erlang/OTP 21.0 and unbreak RabbitMQ 3.7.x with the upcoming Erlang/OTP 23.0.
=> Bump minimum requirement to Erlang/OTP 21.3

mk/rabbitmq-run.mk
This is unused by RabbitMQ after the completion of rabbitmq/rabbitmq-server#2180.
=> rabbitmq-run.mk: Remove uses of $RABBITMQ_SCHEMA_DIR

src/worker_pool.erl, src/worker_pool_worker.erl, test/worker_pool_SUITE.erl
`dispatch_sync` sits in between the behavior of `submit` and `submit_async`, blocking the caller until a worker begins the task (`submit` blocks until the task is scheduled and complete, while `submit_async` does not block at all).
This is useful when you want to throttle submissions to the pool from a single process, such that all workers are busy, but there exists no backlog of work for the pool.
=> Add `worker_pool:dispatch_sync` function

mk/rabbitmq-dist.mk
In other words, if instead of cloning the Umbrella, one cloned rabbitmq-server directly, the `install-cli-scripts` recipe would fail to copy the scripts because it assumed `rabbit` was under `$(DEPS_DIR)`.
Now expected places are checked and an error is emitted if the recipe can't find the right one.
=> rabbitmq-dist.mk: Fix `install-cli-scripts` when rabbit is top-level

mk/rabbitmq-dist.mk
The double-quoting was requited in the flock(1)/lockf(1) blocks because of the use of `sh -c`. However it's incorrect in the `else` block.
Follow-up to commit 1bfff5bb49aa8da5653458c7a4c6ff52eeebe9ff.
=> rabbitmq-dist.mk: Fix incorrect quoting in install-cli-scripts

mk/rabbitmq-run.mk, mk/rabbitmq-tools.mk
Fixes #374
Tested on FreeBSD 12 and Debian Buster. Ran `run-broker` and `start-cluster` on each, worked as expected.
On Windows using msys2, `run-broker` works. `start-cluster` needs work, but not related to this.
=> Use "hostname -s" only on Darwin/FreeBSD

mk/rabbitmq-tools.mk
It generates a file called `$(PROJECT)-rabbitmq-deps.mk` which has a dependency definition line of the form expected by Erlang.mk, for each RabbitMQ component the project depends on.
Therefore the line indicates:
* `git` as the fetch method
* the repository URL
* the Git commit hash the dependency is on
Here is an example for rabbitmq-server:
dep_rabbit_common := git https://github.com/rabbitmq/rabbitmq-common.git d9ccd8d9cdd58310901f318fed676aff59be5afb
dep_rabbitmq_cli := git https://github.com/rabbitmq/rabbitmq-cli.git f6eaae292d27da4ded92b7c1b51a8ddcfefa69c2
dep_rabbitmq_codegen := git https://github.com/rabbitmq/rabbitmq-codegen.git 65da2e86bd65c6b6ecd48478ab092721696bc709
=> rabbitmq-tools.mk: New `rabbitmq-deps.mk` target

mk/rabbitmq-tools.mk
The comment is on the first line of the `$(PROJECT)-rabbitmq-deps.mk` file.
=> rabbitmq-tools.mk: Add project name & commit hash as a comment in rabbitmq-deps.mk

src/rabbit_env.erl, test/rabbit_env_SUITE.erl
... and their value.
Both prefixed and non-prefixed variables are returned by this function.
While here, fix a conflict between `$RABBITMQ_HOME` and `$HOME` in `var_is_used/1`: the latter shouldn't be considered as used.
=> rabbit_env: Add get_used_env_vars/0 to fetch variables used by rabbit_env

include/rabbit.hrl
The default timeout of 30 seconds was not sufficient to allow graceful shutdown of a message store with millions of persistent messages. Rather than increase the timeout in general, introduce a new macro with a default of 600 seconds
=> Add a specific shutdown timeout macro and property for message stores

src/rabbit_env.erl
When we source the `$CONF_ENV_FILE` script, we set a few variables which this script expects. Those variables are given without their prefix. For instance, `$MNESIA_BASE`.
The `$CONF_ENV_FILE` script can set `$RABBITMQ_MNESIA_BASE`. Unfortunately before this patch, the variable would be ignored, in favor of the default value which was passed to the script (`$MNESIA_BASE`).
The reason is that variables set by the script are handled in the alphabetical order. Thus `$MNESIA_BASE` is handled first, then `$RABBITMQ_MNESIA_BASE`.
Because the code didn't give any precedence, the first variable set would "win". This explains why users who set `$RABBITMQ_MNESIA_BASE` in `$CONF_ENV_FILE`, but using RabbitMQ 3.8.4+ (which introduced `rabbit_env`), unexpectedly had their node use the default Mnesia …
=> rabbit_env: Give precedence to $RABBITMQ_* prefixed variables in the output of $CONF_ENV_FILE

mk/rabbitmq-dist.mk
The benefits for doing this:
* We can use native code, as is the case for lz4 and zstd bindings in the Tanzu RabbitMQ version for instance. Indeed, Erlang does not support loading native code (NIF or port drivers) from .ez archives.
* We can remove custom code to handle .ez archives. We have special cases in Erlang.mk plugins as well as the `rabbit_plugins` module, in particular the code to extract .ez archives (even though Erlang knows how to use them directly).
* Prevent hard to debug situations when the .ez archive name does not match the top-level directory inside the archive. In this case, Erlang says it can't load the application but doesn't tell much more.
* Debugging and "hot-patching" plugins become easier: we just have to copy the recompiled .beam file in place of the existing …
=> rabbitmq-dist.mk: Package plugins as directories by default instead of .ez archives

src/rabbit_nodes_common.erl, src/rabbit_runtime.erl, test/unit_SUITE.erl
On Windows, the current working directory is also searched, which can
lead to problems. Instead, use `init:get_argument(root)` to get the root
of the Erlang release, then we know `bin/erl` will always be present.
=> Avoid using os:find_executable to find erl

src/rabbit_ssl_options.erl
As OTP23 is released and is supporting TLSv1.3 by default, removed TLSv1.3 from list of bad SSL protocols
=> remove TLSv1.3 from BAD_SSL_PROTOCOL_VERSIONS

src/rabbit_env.erl, test/rabbit_env_SUITE.erl
The `set` command in the implementation of `/bin/sh` included in the official RabbitMQ Docker image returns multi-line variable values differently than the tested Bourne shell implementation (GNU Bash, dash and FreeBSD sh).
I don't know what implementation is used by that Docker image, but here is the output of `set`, for a variable set to "\n'test'":
TEST_VAR='
'"'"'test'"'"
The problem was reported in the following discussion:
https://github.com/rabbitmq/rabbitmq-server/discussions/2458
While here, add a small testcase to check a couple outputs.
=> rabbit_env: Fix parsing of $CONF_ENV_FILE output

mk/rabbitmq-components.mk
This will enable stacktraces in the logs again.
The `rabbitmq-components.mk` file will need to be updated in all repositories. /cc @dumbbell 
I have tested this against auth_backend_http, auth_backend_oauth2, management, web_dispatch, web_mqtt, web_stomp and everything is green. Therefore I do not think there needs to be any code change to upgrade. /cc @michaelklishin
=> Update Cowboy to 2.8.0
