rabbitmq/rabbitmq-common

src/rabbit_channel.erl
=> channel.open on opened channel should throw channel_error

src/rabbit_reader.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/237.
=> Adds handling of protocol errors on connection establishment.

src/rabbit_channel.erl, src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/419, includes #9, #10, #11, #12.
=> More sensible error messages for connection-level exceptions on running connections

src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/320.
=> Better error message for connections to non-existent vhosts

src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/353. Based on https://github.com/rabbitmq/rabbitmq-common/pull/9, so please merge that first.
=> Improve log message for abruptly closed TCP connections

src/rabbit_channel.erl, src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/416. Builds on top of #9 and #10.
=> More sensible formatting for channel-level exceptions

src/rabbit_channel.erl, src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/418, includes #9, #10, #11.
=> More sensible error messages for non-local connections and failing connection tuning

src/rabbit_control_misc.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/417
=> Reports CTL errors back to user

mk/rabbitmq-run.mk, src/rabbit_amqqueue.erl, src/rabbit_backing_queue.erl
This is should be reviewed together with https://github.com/rabbitmq/rabbitmq-server/pull/377
=> Implements Lazy Queues

src/rabbit_backing_queue.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/429
=> adds new zip_msgs_and_acks/4 callback

src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/434, introduced in 51422941644a371f5b586aa50f01e142a9224ab6.
=> Respect authentication failure notification capability here

src/rabbit_reader.erl
=> Restore the handshake timeout functionality in rabbit_reader

src/rabbit_control_misc.erl
=> fixes specs and warnings

src/credit_flow.erl, src/mirrored_supervisor.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/441
=> fixes dialyzer warnings

src/rabbit_amqqueue.erl
Looks like rabbit_mnesia:is_process_alive/1 check mentioned in comments
there is not sufficient - there was a rabbitmq instance that spent more
than 2 days in this loop.
It should improve situation described in https://github.com/rabbitmq/rabbitmq-server/issues/349 - in some reasonable amount of time client will be unblocked and crash report will be logged.
=> Add retry limit to rabbit_amqqueue:with/2,3

src/rabbit_amqqueue.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/413
=> logs warning when queues_to_recover > available file handles

src/rabbit_reader.erl
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/384 in the only
possible (portable) way - heartbeat sender detects dead socket during
normal operation and notifies rabbit_reader about this fact. This is
especially good given the recent decrease of default heartbeat timeout
to 60 seconds.
This way dead socket will be detected at most in 2 heartbeat
timeouts (as the first write to dropped socket will actually succeed).
Other probable fixes are non-portable or probably not worth it:
- Some unix versions allow to get a TCP connection state using
getsockopt, but there is no such option for Windows.
- 'netstat' output could be parsed periodically, but I'm not sure that
the overhead is comparable with a problem we are trying to solve.
=> Detect connections dropped during resource alarm

codegen.py, src/rabbit_amqqueue.erl, src/rabbit_binary_generator.erl, src/rabbit_binary_parser.erl, src/rabbit_misc.erl
Added few unsigned types for better compatibility with AMQP-0-9-1
https://github.com/rabbitmq/rabbitmq-server/issues/20
=> Unsigned field types to support AMQP-0-9-1

mk/rabbitmq-components.mk
See https://github.com/rabbitmq/rabbitmq-web-stomp/issues/34
=> Update Ranch to 1.2.1

src/rabbit_reader.erl
This is the PR for https://github.com/rabbitmq/rabbitmq-server/issues/520
=> Added direct_reply_to capability declaration.

src/rabbit_networking.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/528
=> Make number of Ranch acceptors configurable

Makefile, mk/rabbitmq-build.mk, mk/rabbitmq-plugin.mk, src/lager_forwarder_backend.erl, src/rabbit_channel.erl, src/rabbit_reader.erl
Fixes rabbitmq/rabbitmq-server#94.
See main pull request: rabbitmq/rabbitmq-server#491.
=> Switch to Lager for logging

.travis.yml, src/rabbit_misc.erl, src/rabbit_nodes.erl
Needed by https://github.com/rabbitmq/rabbitmq-server/pull/552
=> Move random helper to rabbit_misc

mk/rabbitmq-build.mk, src/rabbit_amqqueue.erl, src/rabbit_queue_collector.erl
Related to https://github.com/rabbitmq/rabbitmq-server/pull/611
=> Pass connection Pid to exclusive queue deletion.

src/rabbit_channel.erl
Ref: rabbitmq/rabbitmq-server#248
=> Ignore result from notify_queues/1

src/rabbit_channel.erl
=> Ignore notify_queues/1 result in rabbit_channel:terminate/2

src/rabbit_amqqueue.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/688
=> Add support for listing up/down queues

src/code_version.erl
Before this patch, concurrent calls to `code_version` for the same module would lead to one call succeeding and the other calls getting an exception because the code server complains about a non-purged copy.
Now:
1. We acquire a lock for the given module name
2. We check the filename of the already loaded module to replace: if it matches the fake filename used by the reload, it means the module was replaced in a concurrent call. The next step is skipped.
3. We reload the module.
4. We release the lock.
Fixes #73.
=> code_version: Acquire a lock to protect concurrent reloads

src/rabbit_misc.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/151
=> Guess thread pool size on startup

src/rabbit_error_logger_handler.erl, src/rabbit_nodes.erl
Closes https://github.com/rabbitmq/rabbitmq-server/issues/401
=> Capture detailed Erlang logs on connection failure

include/rabbit.hrl
Related to https://github.com/rabbitmq/rabbitmq-server/pull/642
https://github.com/rabbitmq/rabbitmq-server/issues/591
=> rabbitmq_versions key for plugin

include/rabbit.hrl, src/rabbit_networking.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/163
=> Save listener socket options in Mnesia

src/rabbit_channel.erl
Fixes rabbitmq/rabbitmq-server#710.
=> Strip LF and CR off of names in {queue,exchange}.{declare,delete,bind,unbind}

src/rabbit_auth_backend_internal.erl
Vhost is added to auth properties in https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/13
=> Support arbitrary AuthProps proplists

src/rabbit_misc.erl
Required for build releases.
https://github.com/rabbitmq/rabbitmq-server/issues/735
=> Support 4 number versions

src/mirrored_supervisor.erl
Solves https://github.com/rabbitmq/rabbitmq-management/issues/174
=> Restart the children using the order provided to the supervisor

mk/rabbitmq-run.mk
=> Do not use ?= operator in make target env variables setup

include/rabbit.hrl, src/rabbit_amqqueue.erl, src/rabbit_ct_broker_helpers.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/803
=> Handle concurrent application of HA policy

src/rabbit_misc.erl
Part of rabbitmq/rabbitmq-server#820
=> Part of rabbitmq/rabbitmq-server#820

src/rabbit_amqqueue.erl
These are purely for convenience.
Primarily intended to be used from `rabbitmqctl eval`
or REPL when investigating issues or to inspect/restart individual
queues.
=> Introduce rabbit_amqqueue:pid_of/{1, 2}

src/rabbit_ct_broker_helpers.erl
Part of https://github.com/rabbitmq/rabbitmq-web-mqtt/issues/12
https://github.com/rabbitmq/rabbitmq-web-mqtt/pull/13
=> Enable generation of mqtt and web-mqtt ports

include/rabbit.hrl, src/rabbit_amqqueue.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/863
=> Include slave_pids_pending_shutdown on amqqueue record

src/rabbit_channel.erl, src/rabbit_reader.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/211
=> Report reductions and garbage collection options in connection stats

src/rabbit_channel.erl, src/rabbit_misc.erl, src/rabbit_reader.erl
Solves https://github.com/rabbitmq/rabbitmq-management/issues/244
=> Use rabbit_misc to parse GC stats, supporting maps in R19

src/rabbit_common.app.src
=> Add `xmerl` dependency to `.app.src`

src/rabbit_amqqueue.erl
The other part of https://github.com/rabbitmq/rabbitmq-server/pull/911
=> Add support for listing only local queues

src/rabbit_health_check.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/915
=> Check rabbit_node_monitor during health-check

src/rabbit_reader.erl
Fixes part of: https://github.com/rabbitmq/rabbitmq-erlang-client/issues/68
To go with changes to the erlang client test suite expected return codes.
=> translate thrown no_such_vhost exception into not_found protocol error

src/mochinum.erl
See rabbitmq/rabbitmq-server#941
Fixes  rabbitmq/rabbitmq-server#940.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> Move mochium to rabbitmq-common

include/rabbit.hrl, src/rabbit_ct_broker_helpers.erl, src/rabbit_registry.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/938 
https://github.com/rabbitmq/rabbitmq-server/issues/930
=> Operator policies data structures

include/rabbit.hrl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/958
https://github.com/rabbitmq/rabbitmq-server/issues/948
=> Type field in tracked_connection record to track direct and network connections

src/mirrored_supervisor.erl
References rabbitmq/rabbitmq-server#980.
[#131354699]
=> mirrored_supervisor: Use the standard `pg2` module

src/rabbit_channel.erl
Closes https://github.com/rabbitmq/rabbitmq-server/issues/1005
=> Ignore late answers to the channel

mk/rabbitmq-dist.mk
Without this change applications in `apps/` were compiled, but not
bundled into `.ez` files.
=> Create .ez for multi-app plugins

src/rabbit_auth_backend_internal.erl, src/rabbit_data_coercion.erl
=> Convert input user tags into appropriate type

src/rabbit_data_coercion.erl
Part of rabbitmq/rabbitmq-server#1030
=> Add rabbit_data_coercion:to_integer/1

src/rabbit_data_coercion.erl
References rabbitmq/rabbitmq-mqtt#86
=> Backport to_list, to_atom, to_integer

src/rabbit_core_metrics.erl
`ets:update_counter/4` was added to Erlang 18.x. Thus we need a wrapper to support Erlang down to R16B03.
This wrapper uses `ets:insert_new/2` first, then `ets:update_counter/3`. It lacks the atomicity of `ets:update_counter/4`, so if the entry was removed in between, the exception is simply ignored.
To avoid any penalty on Erlang 18+, we use `code_version` to load the appropriate version of the wrapper at runtime. Thus we still use `ets:udpate_counter/4` on Erlang 18+.
[#135769137]
=> rabbit_core_metrics: Restore compatibility with Erlang R16B03/17.x

mk/rabbitmq-build.mk, src/rabbit_data_coercion.erl, src/rabbit_nodes.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1058
=> Support tests with the new CLI

src/rabbit_auth_backend_internal.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1054.
=> Introduce credential validation

include/rabbit.hrl, src/rabbit_auth_backend_dummy.erl, src/rabbit_auth_backend_internal.erl, src/rabbit_authz_backend.erl, src/rabbit_channel.erl, src/rabbit_misc.erl, src/rabbit_nodes.erl, src/rabbit_types.erl
Part of rabbitmq/rabbitmq-server#505.
=> Topic-based authorisation for publishes

include/rabbit.hrl, src/rabbit_amqqueue.erl, src/rabbit_auth_backend_internal.erl, src/rabbit_channel.erl, src/rabbit_nodes.erl, src/rabbit_reader.erl, src/rabbit_runtime_parameter.erl
Part of https://github.com/rabbitmq/rabbitmq-event-exchange/issues/10
=> Notify user who performed the action in all system events

src/rabbit_json.erl
Part of https://github.com/rabbitmq/rabbitmq-common/issues/164.
=> Add the Options parameter

include/rabbit.hrl, src/rabbit_auth_backend_internal.erl, src/rabbit_authz_backend.erl, src/rabbit_channel.erl, src/rabbit_types.erl
Part of rabbitmq/rabbitmq-server#1085
=> Add topic authorisation for consumption

src/rabbit_backing_queue.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/345
=> Include paged out stats

src/rabbit_net.erl, src/rabbit_reader.erl
References rabbitmq/rabbitmq-server#589, rabbitmq/rabbitmq-amqp1.0#44
=> Forward proxy socket to AMQP 1.0 reader

include/rabbit_core_metrics.hrl, src/gen_server2.erl, src/rabbit_core_metrics.erl
Part of https://github.com/rabbitmq/rabbitmq-top/issues/20
=> Emit gen_server2 buffer length stats

src/rabbit_channel.erl
Fixes rabbitmq/rabbitmq-server#1099
=> Apply consumer topic permissions to queue.{bind, unbind}

src/rabbit_amqqueue.erl
Used by https://github.com/rabbitmq/rabbitmq-management-agent/issues/25
=> Function to retrieve all queue names (keys)

src/rabbit_msg_store_index.erl
Part of rabbitmq/rabbitmq-server#1123
=> Clarify msg_store_index API. Change API for delete_by_file

include/rabbit.hrl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1124
=> Add extra_dependencies on plugin record

mk/rabbitmq-plugin.mk, mk/rabbitmq-test.mk
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1136
=> Makefile plugin for fast and slow test suites

src/rabbit_reader.erl
Fixes rabbitmq/rabbitmq-server#1140.
=> Log username and vhost on successful connection.open

src/gen_server2.erl
=> Stop emitting stats before hibernate on gen_server2

src/supervisor2.erl
This is #201 by @aartamonau branched off of and re-submitted against the `stable` branch.
=> Re-submitted #201 against `stable`

src/rabbit_peer_discovery_backend.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1257
=> Add lock and unlock to peer discovery backend

src/delegate.erl
=> Reduce binary heap growth in delegate:cast/2

.travis.yml, include/rabbit.hrl
Part of rabbitmq/rabbitmq-server#1305.
[#149563549]
=> Require Erlang/OTP 19.2 (erts 8.2)

src/rabbit_misc.erl
Related to rabbitmq/rabbitmq-server#1303
[#148409695]
=> An error message for queues, stopped by a vhost supervisor.

src/app_utils.erl
In commit faf1603afe6b47feee9cf02cb4a2054f844956eb @dumbbell noted that the changes ported from `stable` do not specify a `transient` restart type for the `rabbit` application.
This PR ensures that an application is started with the specified restart type as well as starts its dependencies.
=> Port ensure_all_started and modify to use RestartTypes map

include/rabbit.hrl
=> include/rabbit.hrl: Bump Erlang requirement to 19.3 (ERTS 8.3)

src/vm_memory_monitor.erl
Follow up to https://github.com/rabbitmq/rabbitmq-management/issues/499
=> Add API to get rss memory

src/rabbit_data_coercion.erl, test/unit_SUITE.erl
Part of rabbitmq/rabbitmq-management#528, rabbitmq/rabbitmq-mqtt#156.
=> Introduce rabbit_data_coercion:{to_map/1, to_proplist/1}

include/rabbit.hrl
Reverts rabbitmq/rabbitmq-common#247
=> Revert "Extend amqqueue record to include queue type"

src/rabbit_misc.erl
Part of rabbitmq/rabbitmq-server#1522, rabbitmq/rabbitmq-server#1524.
See the discussion in rabbitmq/rabbitmq-server#1524 and rabbitmq/rabbitmq-server#1522 for details.
=> Handle {ongoing_change_to, NewValue} responses (master)

src/rabbit_amqp_connection.erl
Fixes rabbitmq/rabbitmq-server#1538
=> Check process before getting amqp_params

src/rabbit_amqp_connection.erl
Part of rabbitmq/rabbitmq-server#1538
=> Merge rabbitmq-server-1538 to master

src/rabbit_auth_backend_dummy.erl, src/rabbit_authz_backend.erl
Part of rabbitmq/rabbitmq-server#1633.
[#158805410]
=> Pass authentication context to Mod:user_login_authorization/2

include/rabbit_core_metrics.hrl, src/rabbit_core_metrics.erl
Rate metrics for monitoring of high connection churn scenarios
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1723
=> Report connection/channel/queue churn

src/rabbit_heartbeat.erl
When a heartbeat handler is run, the socket stats should be re-collected because the act of running the handler can affect the stats (like sent bytes).
See https://groups.google.com/d/topic/rabbitmq-users/djNpSuQoznY/discussion
=> Update socket stats after running handler

mk/rabbitmq-components.mk
The promised releases to fix PROXY issues. Please merge before next Tuesday so that I can finally finalize the many PRs that are waiting. :-) @dumbbell
=> Update Ranch to 1.7.1 and Cowboy to 2.6.1

Makefile, mk/rabbitmq-components.mk, src/rabbit_net.erl
This set of PRs is ready. Other PRs in the set:
* https://github.com/rabbitmq/rabbitmq-server/pull/1747
* https://github.com/rabbitmq/rabbitmq-mqtt/pull/167
* https://github.com/rabbitmq/rabbitmq-stomp/pull/127
=> Use the built-in Ranch PROXY protocol support

src/priority_queue.erl, test/unit_priority_queue_SUITE.erl
References rabbitmq/rabbitmq-server#1799.
=> Single active consumer in quorum queue

src/rabbit_heartbeat.erl
Per discussion with @lukebakken.
=> Introduce a new type, heartbeat_timeout, for documentation purposes

src/rabbit_core_metrics.erl
[#163298456]
References rabbitmq/rabbitmq-server#1838
=> Add activity status field to consumer created

src/rabbit_log.erl, src/rabbit_log_ra.erl
And make a new logging category for Ra logs
[#163518117]
=> Add rabbit_log_ra shim

src/rabbit_runtime.erl
Part of https://github.com/rabbitmq/rabbitmq-cli/issues/319.
=> Introduce rabbit_runtime:gc_all_processes/0

include/rabbit.hrl, src/rabbit_auth_backend_dummy.erl, src/rabbit_authz_backend.erl, src/rabbit_types.erl
Fixes rabbitmq/rabbitmq-auth-backend-cache#22
=> Cache vhost access requests using client IP address only

src/vm_memory_monitor.erl
Previous behavior is to crash, this is more forgiving
Fixes #318
=> Handle missing getconf command

mk/rabbitmq-build.mk, src/rabbit_log.erl
Drive-by change that is now part of rabbitmq/rabbitmq-shovel#61.
References rabbitmq/rabbitmq-shovel#60.
[#166627333]
=> New Lager sink for Shovel

src/worker_pool_sup.erl
Part of rabbitmq/rabbitmq-server#2030.
=> Make default worker pool size configurable

src/rabbit_control_misc.erl, src/worker_pool_worker.erl
See http://erlang.org/doc/efficiency_guide/commoncaveats.html#timer-module
=> Replace timer:send_after/3 by erlang:send_after/3

include/rabbit.hrl, src/rabbit_types.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/2012
=> Add vhost description and tags fields

src/rabbit_misc.erl
=> Special-case x-queue-type classic/undefined

src/rabbit_misc.erl, test/unit_SUITE.erl
Part of rabbitmq/rabbitmq-management#749.
=> Move some helpers from rabbitmq-management

mk/rabbitmq-tools.mk
If there are common_test logs (i.e. `logs` exists), it creates an archive (compressed with xz(1)) in the top-level directory.
The archive is named `$(PROJECT)-ct-logs-$timestamp.tar.xz` by default. The filename and location can be changed by setting `$(CT_LOGS_ARCHIVE)`. The file extension must be `.tar.xz`.
=> rabbitmq-tools.mk: Add compress-ct-logs target

Makefile, src/rabbit_pbe.erl
Part of the following:
https://github.com/rabbitmq/credentials-obfuscation/pull/5
=> Update to credentials_obfuscation 2.0

src/rabbit_pbe.erl
In follow-up to rabbitmq/rabbitmq-server#2351, #389.
=> Update type specs in rabbit_pbe

src/rabbit_types.erl
Part of rabbitmq/rabbitmq-server#2356.
=> Introduce rabbit_types:error/2

src/rabbit_env.erl, test/rabbit_env_SUITE.erl
=> Add support for RABBITMQ_CONF_ENV_FILE on Windows

src/rabbit_net.erl
Part of rabbitmq/rabbitmq-cli#424
=> Introduce a way to list available NICs in a more presentable format

src/rabbit_log.erl
This allows RabbitMQ to configure `rabbit_log` as a Logger handler.
See a related commit in rabbit_prelaunch_early_logging in rabbitmq-server, where `rabbit_log` is being configured as a Logger
handler. The commit message explains the reason behind this.
References rabbitmq/rabbitmq-server#2401.
=> rabbit_log: Add Logger handler's log/2 API

include/rabbit.hrl, test/worker_pool_SUITE.erl
Part of rabbitmq/rabbitmq-server#2321.
=> Add a record for node maintenance state

mk/rabbitmq-dist.mk
https://github.com/rabbitmq/mix_task_archive_deps/releases/tag/0.5.0
See this as well:
https://github.com/rabbitmq/mix_task_archive_deps/pull/2
https://groups.google.com/d/topic/rabbitmq-users/0d8TBs_qmGE/discussion
cc @noxdafox
=> Update mix_task_archive_deps version

mk/rabbitmq-build.mk, mk/rabbitmq-run.mk, src/rabbit_env.erl, src/rabbit_log.erl, src/rabbit_log_osiris_shim.erl, src/rabbit_misc.erl, test/rabbit_env_SUITE.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/2347
=> Stream queue

include/rabbit_core_metrics.hrl, src/rabbit_core_metrics.erl
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2436
=> Add auth attempt metrics

src/file_handle_cache.erl
CI failures such as this suggest that file handle values can be deleted
mid-operation:
https://github.com/rabbitmq/rabbitmq-server/actions/runs/304216635
=> Handle potential undefined value returned from process dictionary

src/rabbit_misc.erl
Part of rabbitmq/rabbitmq-server#2473
=> Remove code to guess thread pool size
